name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello NagaShankar, welcome to GitHub Actions crash course!"
      - name: Print goodbye
        run: echo "All the best for your preparation!"
